// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafka.proto

#include "kafka.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace KafkaConsumerServer {
class ConsumerJobDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConsumerJob>
      _instance;
} _ConsumerJob_default_instance_;
class JobIDDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<JobID>
      _instance;
} _JobID_default_instance_;
class BatchDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BatchData>
      _instance;
} _BatchData_default_instance_;
class BatchInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BatchInfo>
      _instance;
} _BatchInfo_default_instance_;
class EmptyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Empty>
      _instance;
} _Empty_default_instance_;
}  // namespace KafkaConsumerServer
namespace protobuf_kafka_2eproto {
static void InitDefaultsConsumerJob() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KafkaConsumerServer::_ConsumerJob_default_instance_;
    new (ptr) ::KafkaConsumerServer::ConsumerJob();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KafkaConsumerServer::ConsumerJob::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConsumerJob =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConsumerJob}, {}};

static void InitDefaultsJobID() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KafkaConsumerServer::_JobID_default_instance_;
    new (ptr) ::KafkaConsumerServer::JobID();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KafkaConsumerServer::JobID::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_JobID =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsJobID}, {}};

static void InitDefaultsBatchData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KafkaConsumerServer::_BatchData_default_instance_;
    new (ptr) ::KafkaConsumerServer::BatchData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KafkaConsumerServer::BatchData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BatchData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBatchData}, {}};

static void InitDefaultsBatchInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KafkaConsumerServer::_BatchInfo_default_instance_;
    new (ptr) ::KafkaConsumerServer::BatchInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KafkaConsumerServer::BatchInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BatchInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBatchInfo}, {}};

static void InitDefaultsEmpty() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KafkaConsumerServer::_Empty_default_instance_;
    new (ptr) ::KafkaConsumerServer::Empty();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KafkaConsumerServer::Empty::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Empty =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEmpty}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ConsumerJob.base);
  ::google::protobuf::internal::InitSCC(&scc_info_JobID.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BatchData.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BatchInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Empty.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, topic_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, brokers_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, partitionid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, offset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, batchinterval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, batchsize_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, destination_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::ConsumerJob, format_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::JobID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::JobID, id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchData, data_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchInfo, lastoffset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchInfo, eof_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchInfo, errorcode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::BatchInfo, errormessage_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KafkaConsumerServer::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::KafkaConsumerServer::ConsumerJob)},
  { 13, -1, sizeof(::KafkaConsumerServer::JobID)},
  { 19, -1, sizeof(::KafkaConsumerServer::BatchData)},
  { 25, -1, sizeof(::KafkaConsumerServer::BatchInfo)},
  { 34, -1, sizeof(::KafkaConsumerServer::Empty)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::KafkaConsumerServer::_ConsumerJob_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KafkaConsumerServer::_JobID_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KafkaConsumerServer::_BatchData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KafkaConsumerServer::_BatchInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KafkaConsumerServer::_Empty_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "kafka.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013kafka.proto\022\023KafkaConsumerServer\"\241\001\n\013C"
      "onsumerJob\022\r\n\005Topic\030\001 \001(\t\022\017\n\007Brokers\030\002 \001"
      "(\t\022\023\n\013PartitionID\030\003 \001(\005\022\016\n\006Offset\030\004 \001(\003\022"
      "\025\n\rBatchInterval\030\005 \001(\005\022\021\n\tBatchSize\030\006 \001("
      "\005\022\023\n\013Destination\030\007 \001(\t\022\016\n\006Format\030\010 \001(\t\"\023"
      "\n\005JobID\022\n\n\002ID\030\001 \001(\t\"\031\n\tBatchData\022\014\n\004Data"
      "\030\001 \003(\014\"U\n\tBatchInfo\022\022\n\nLastOffset\030\001 \001(\003\022"
      "\013\n\003EOF\030\002 \001(\010\022\021\n\tErrorCode\030\003 \001(\005\022\024\n\014Error"
      "Message\030\004 \001(\t\"\007\n\005Empty2\263\002\n\005Kafka\022H\n\006AddJ"
      "ob\022 .KafkaConsumerServer.ConsumerJob\032\032.K"
      "afkaConsumerServer.JobID\"\000\022E\n\tDeleteJob\022"
      "\032.KafkaConsumerServer.JobID\032\032.KafkaConsu"
      "merServer.Empty\"\000\022K\n\tReadBatch\022\032.KafkaCo"
      "nsumerServer.JobID\032\036.KafkaConsumerServer"
      ".BatchData\"\0000\001\022L\n\014GetBatchInfo\022\032.KafkaCo"
      "nsumerServer.JobID\032\036.KafkaConsumerServer"
      ".BatchInfo\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 660);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kafka.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_kafka_2eproto
namespace KafkaConsumerServer {

// ===================================================================

void ConsumerJob::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConsumerJob::kTopicFieldNumber;
const int ConsumerJob::kBrokersFieldNumber;
const int ConsumerJob::kPartitionIDFieldNumber;
const int ConsumerJob::kOffsetFieldNumber;
const int ConsumerJob::kBatchIntervalFieldNumber;
const int ConsumerJob::kBatchSizeFieldNumber;
const int ConsumerJob::kDestinationFieldNumber;
const int ConsumerJob::kFormatFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConsumerJob::ConsumerJob()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kafka_2eproto::scc_info_ConsumerJob.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KafkaConsumerServer.ConsumerJob)
}
ConsumerJob::ConsumerJob(const ConsumerJob& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  topic_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.topic().size() > 0) {
    topic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.topic_);
  }
  brokers_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.brokers().size() > 0) {
    brokers_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brokers_);
  }
  destination_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.destination().size() > 0) {
    destination_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destination_);
  }
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.format().size() > 0) {
    format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
  }
  ::memcpy(&offset_, &from.offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&batchsize_) -
    reinterpret_cast<char*>(&offset_)) + sizeof(batchsize_));
  // @@protoc_insertion_point(copy_constructor:KafkaConsumerServer.ConsumerJob)
}

void ConsumerJob::SharedCtor() {
  topic_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brokers_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&offset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&batchsize_) -
      reinterpret_cast<char*>(&offset_)) + sizeof(batchsize_));
}

ConsumerJob::~ConsumerJob() {
  // @@protoc_insertion_point(destructor:KafkaConsumerServer.ConsumerJob)
  SharedDtor();
}

void ConsumerJob::SharedDtor() {
  topic_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brokers_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConsumerJob::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConsumerJob::descriptor() {
  ::protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConsumerJob& ConsumerJob::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kafka_2eproto::scc_info_ConsumerJob.base);
  return *internal_default_instance();
}


void ConsumerJob::Clear() {
// @@protoc_insertion_point(message_clear_start:KafkaConsumerServer.ConsumerJob)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  topic_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  brokers_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  destination_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&offset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&batchsize_) -
      reinterpret_cast<char*>(&offset_)) + sizeof(batchsize_));
  _internal_metadata_.Clear();
}

bool ConsumerJob::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KafkaConsumerServer.ConsumerJob)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string Topic = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_topic()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->topic().data(), static_cast<int>(this->topic().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KafkaConsumerServer.ConsumerJob.Topic"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Brokers = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_brokers()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->brokers().data(), static_cast<int>(this->brokers().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KafkaConsumerServer.ConsumerJob.Brokers"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 PartitionID = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &partitionid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Offset = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &offset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 BatchInterval = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &batchinterval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 BatchSize = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &batchsize_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Destination = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_destination()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->destination().data(), static_cast<int>(this->destination().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KafkaConsumerServer.ConsumerJob.Destination"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Format = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_format()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->format().data(), static_cast<int>(this->format().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KafkaConsumerServer.ConsumerJob.Format"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KafkaConsumerServer.ConsumerJob)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KafkaConsumerServer.ConsumerJob)
  return false;
#undef DO_
}

void ConsumerJob::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KafkaConsumerServer.ConsumerJob)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Topic = 1;
  if (this->topic().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->topic().data(), static_cast<int>(this->topic().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Topic");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->topic(), output);
  }

  // string Brokers = 2;
  if (this->brokers().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brokers().data(), static_cast<int>(this->brokers().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Brokers");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->brokers(), output);
  }

  // int32 PartitionID = 3;
  if (this->partitionid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->partitionid(), output);
  }

  // int64 Offset = 4;
  if (this->offset() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->offset(), output);
  }

  // int32 BatchInterval = 5;
  if (this->batchinterval() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->batchinterval(), output);
  }

  // int32 BatchSize = 6;
  if (this->batchsize() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->batchsize(), output);
  }

  // string Destination = 7;
  if (this->destination().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->destination().data(), static_cast<int>(this->destination().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Destination");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->destination(), output);
  }

  // string Format = 8;
  if (this->format().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format().data(), static_cast<int>(this->format().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Format");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->format(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KafkaConsumerServer.ConsumerJob)
}

::google::protobuf::uint8* ConsumerJob::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KafkaConsumerServer.ConsumerJob)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Topic = 1;
  if (this->topic().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->topic().data(), static_cast<int>(this->topic().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Topic");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->topic(), target);
  }

  // string Brokers = 2;
  if (this->brokers().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brokers().data(), static_cast<int>(this->brokers().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Brokers");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->brokers(), target);
  }

  // int32 PartitionID = 3;
  if (this->partitionid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->partitionid(), target);
  }

  // int64 Offset = 4;
  if (this->offset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->offset(), target);
  }

  // int32 BatchInterval = 5;
  if (this->batchinterval() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->batchinterval(), target);
  }

  // int32 BatchSize = 6;
  if (this->batchsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->batchsize(), target);
  }

  // string Destination = 7;
  if (this->destination().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->destination().data(), static_cast<int>(this->destination().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Destination");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->destination(), target);
  }

  // string Format = 8;
  if (this->format().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format().data(), static_cast<int>(this->format().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.ConsumerJob.Format");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->format(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KafkaConsumerServer.ConsumerJob)
  return target;
}

size_t ConsumerJob::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KafkaConsumerServer.ConsumerJob)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string Topic = 1;
  if (this->topic().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->topic());
  }

  // string Brokers = 2;
  if (this->brokers().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->brokers());
  }

  // string Destination = 7;
  if (this->destination().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->destination());
  }

  // string Format = 8;
  if (this->format().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->format());
  }

  // int64 Offset = 4;
  if (this->offset() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->offset());
  }

  // int32 PartitionID = 3;
  if (this->partitionid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->partitionid());
  }

  // int32 BatchInterval = 5;
  if (this->batchinterval() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->batchinterval());
  }

  // int32 BatchSize = 6;
  if (this->batchsize() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->batchsize());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConsumerJob::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KafkaConsumerServer.ConsumerJob)
  GOOGLE_DCHECK_NE(&from, this);
  const ConsumerJob* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConsumerJob>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KafkaConsumerServer.ConsumerJob)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KafkaConsumerServer.ConsumerJob)
    MergeFrom(*source);
  }
}

void ConsumerJob::MergeFrom(const ConsumerJob& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KafkaConsumerServer.ConsumerJob)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.topic().size() > 0) {

    topic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.topic_);
  }
  if (from.brokers().size() > 0) {

    brokers_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brokers_);
  }
  if (from.destination().size() > 0) {

    destination_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.destination_);
  }
  if (from.format().size() > 0) {

    format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
  }
  if (from.offset() != 0) {
    set_offset(from.offset());
  }
  if (from.partitionid() != 0) {
    set_partitionid(from.partitionid());
  }
  if (from.batchinterval() != 0) {
    set_batchinterval(from.batchinterval());
  }
  if (from.batchsize() != 0) {
    set_batchsize(from.batchsize());
  }
}

void ConsumerJob::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KafkaConsumerServer.ConsumerJob)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConsumerJob::CopyFrom(const ConsumerJob& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KafkaConsumerServer.ConsumerJob)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConsumerJob::IsInitialized() const {
  return true;
}

void ConsumerJob::Swap(ConsumerJob* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConsumerJob::InternalSwap(ConsumerJob* other) {
  using std::swap;
  topic_.Swap(&other->topic_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  brokers_.Swap(&other->brokers_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  destination_.Swap(&other->destination_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  format_.Swap(&other->format_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(offset_, other->offset_);
  swap(partitionid_, other->partitionid_);
  swap(batchinterval_, other->batchinterval_);
  swap(batchsize_, other->batchsize_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConsumerJob::GetMetadata() const {
  protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void JobID::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JobID::kIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JobID::JobID()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kafka_2eproto::scc_info_JobID.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KafkaConsumerServer.JobID)
}
JobID::JobID(const JobID& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.id().size() > 0) {
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  // @@protoc_insertion_point(copy_constructor:KafkaConsumerServer.JobID)
}

void JobID::SharedCtor() {
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

JobID::~JobID() {
  // @@protoc_insertion_point(destructor:KafkaConsumerServer.JobID)
  SharedDtor();
}

void JobID::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void JobID::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* JobID::descriptor() {
  ::protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const JobID& JobID::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kafka_2eproto::scc_info_JobID.base);
  return *internal_default_instance();
}


void JobID::Clear() {
// @@protoc_insertion_point(message_clear_start:KafkaConsumerServer.JobID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool JobID::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KafkaConsumerServer.JobID)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id().data(), static_cast<int>(this->id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KafkaConsumerServer.JobID.ID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KafkaConsumerServer.JobID)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KafkaConsumerServer.JobID)
  return false;
#undef DO_
}

void JobID::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KafkaConsumerServer.JobID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ID = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.JobID.ID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KafkaConsumerServer.JobID)
}

::google::protobuf::uint8* JobID::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KafkaConsumerServer.JobID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ID = 1;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.JobID.ID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KafkaConsumerServer.JobID)
  return target;
}

size_t JobID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KafkaConsumerServer.JobID)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ID = 1;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void JobID::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KafkaConsumerServer.JobID)
  GOOGLE_DCHECK_NE(&from, this);
  const JobID* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const JobID>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KafkaConsumerServer.JobID)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KafkaConsumerServer.JobID)
    MergeFrom(*source);
  }
}

void JobID::MergeFrom(const JobID& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KafkaConsumerServer.JobID)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id().size() > 0) {

    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
}

void JobID::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KafkaConsumerServer.JobID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JobID::CopyFrom(const JobID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KafkaConsumerServer.JobID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JobID::IsInitialized() const {
  return true;
}

void JobID::Swap(JobID* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JobID::InternalSwap(JobID* other) {
  using std::swap;
  id_.Swap(&other->id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata JobID::GetMetadata() const {
  protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void BatchData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BatchData::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BatchData::BatchData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kafka_2eproto::scc_info_BatchData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KafkaConsumerServer.BatchData)
}
BatchData::BatchData(const BatchData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:KafkaConsumerServer.BatchData)
}

void BatchData::SharedCtor() {
}

BatchData::~BatchData() {
  // @@protoc_insertion_point(destructor:KafkaConsumerServer.BatchData)
  SharedDtor();
}

void BatchData::SharedDtor() {
}

void BatchData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BatchData::descriptor() {
  ::protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BatchData& BatchData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kafka_2eproto::scc_info_BatchData.base);
  return *internal_default_instance();
}


void BatchData::Clear() {
// @@protoc_insertion_point(message_clear_start:KafkaConsumerServer.BatchData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _internal_metadata_.Clear();
}

bool BatchData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KafkaConsumerServer.BatchData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bytes Data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KafkaConsumerServer.BatchData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KafkaConsumerServer.BatchData)
  return false;
#undef DO_
}

void BatchData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KafkaConsumerServer.BatchData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes Data = 1;
  for (int i = 0, n = this->data_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->data(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KafkaConsumerServer.BatchData)
}

::google::protobuf::uint8* BatchData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KafkaConsumerServer.BatchData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated bytes Data = 1;
  for (int i = 0, n = this->data_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(1, this->data(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KafkaConsumerServer.BatchData)
  return target;
}

size_t BatchData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KafkaConsumerServer.BatchData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated bytes Data = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->data_size());
  for (int i = 0, n = this->data_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->data(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BatchData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KafkaConsumerServer.BatchData)
  GOOGLE_DCHECK_NE(&from, this);
  const BatchData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BatchData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KafkaConsumerServer.BatchData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KafkaConsumerServer.BatchData)
    MergeFrom(*source);
  }
}

void BatchData::MergeFrom(const BatchData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KafkaConsumerServer.BatchData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
}

void BatchData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KafkaConsumerServer.BatchData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BatchData::CopyFrom(const BatchData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KafkaConsumerServer.BatchData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchData::IsInitialized() const {
  return true;
}

void BatchData::Swap(BatchData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BatchData::InternalSwap(BatchData* other) {
  using std::swap;
  data_.InternalSwap(CastToBase(&other->data_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BatchData::GetMetadata() const {
  protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void BatchInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BatchInfo::kLastOffsetFieldNumber;
const int BatchInfo::kEOFFieldNumber;
const int BatchInfo::kErrorCodeFieldNumber;
const int BatchInfo::kErrorMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BatchInfo::BatchInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kafka_2eproto::scc_info_BatchInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KafkaConsumerServer.BatchInfo)
}
BatchInfo::BatchInfo(const BatchInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  errormessage_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.errormessage().size() > 0) {
    errormessage_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.errormessage_);
  }
  ::memcpy(&lastoffset_, &from.lastoffset_,
    static_cast<size_t>(reinterpret_cast<char*>(&errorcode_) -
    reinterpret_cast<char*>(&lastoffset_)) + sizeof(errorcode_));
  // @@protoc_insertion_point(copy_constructor:KafkaConsumerServer.BatchInfo)
}

void BatchInfo::SharedCtor() {
  errormessage_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&lastoffset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&errorcode_) -
      reinterpret_cast<char*>(&lastoffset_)) + sizeof(errorcode_));
}

BatchInfo::~BatchInfo() {
  // @@protoc_insertion_point(destructor:KafkaConsumerServer.BatchInfo)
  SharedDtor();
}

void BatchInfo::SharedDtor() {
  errormessage_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BatchInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BatchInfo::descriptor() {
  ::protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BatchInfo& BatchInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kafka_2eproto::scc_info_BatchInfo.base);
  return *internal_default_instance();
}


void BatchInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:KafkaConsumerServer.BatchInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  errormessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&lastoffset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&errorcode_) -
      reinterpret_cast<char*>(&lastoffset_)) + sizeof(errorcode_));
  _internal_metadata_.Clear();
}

bool BatchInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KafkaConsumerServer.BatchInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 LastOffset = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &lastoffset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool EOF = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &eof_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 ErrorCode = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &errorcode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string ErrorMessage = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_errormessage()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->errormessage().data(), static_cast<int>(this->errormessage().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KafkaConsumerServer.BatchInfo.ErrorMessage"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KafkaConsumerServer.BatchInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KafkaConsumerServer.BatchInfo)
  return false;
#undef DO_
}

void BatchInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KafkaConsumerServer.BatchInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 LastOffset = 1;
  if (this->lastoffset() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->lastoffset(), output);
  }

  // bool EOF = 2;
  if (this->eof() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->eof(), output);
  }

  // int32 ErrorCode = 3;
  if (this->errorcode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->errorcode(), output);
  }

  // string ErrorMessage = 4;
  if (this->errormessage().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->errormessage().data(), static_cast<int>(this->errormessage().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.BatchInfo.ErrorMessage");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->errormessage(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KafkaConsumerServer.BatchInfo)
}

::google::protobuf::uint8* BatchInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KafkaConsumerServer.BatchInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 LastOffset = 1;
  if (this->lastoffset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->lastoffset(), target);
  }

  // bool EOF = 2;
  if (this->eof() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->eof(), target);
  }

  // int32 ErrorCode = 3;
  if (this->errorcode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->errorcode(), target);
  }

  // string ErrorMessage = 4;
  if (this->errormessage().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->errormessage().data(), static_cast<int>(this->errormessage().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KafkaConsumerServer.BatchInfo.ErrorMessage");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->errormessage(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KafkaConsumerServer.BatchInfo)
  return target;
}

size_t BatchInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KafkaConsumerServer.BatchInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string ErrorMessage = 4;
  if (this->errormessage().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->errormessage());
  }

  // int64 LastOffset = 1;
  if (this->lastoffset() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->lastoffset());
  }

  // bool EOF = 2;
  if (this->eof() != 0) {
    total_size += 1 + 1;
  }

  // int32 ErrorCode = 3;
  if (this->errorcode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->errorcode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BatchInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KafkaConsumerServer.BatchInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const BatchInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BatchInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KafkaConsumerServer.BatchInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KafkaConsumerServer.BatchInfo)
    MergeFrom(*source);
  }
}

void BatchInfo::MergeFrom(const BatchInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KafkaConsumerServer.BatchInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.errormessage().size() > 0) {

    errormessage_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.errormessage_);
  }
  if (from.lastoffset() != 0) {
    set_lastoffset(from.lastoffset());
  }
  if (from.eof() != 0) {
    set_eof(from.eof());
  }
  if (from.errorcode() != 0) {
    set_errorcode(from.errorcode());
  }
}

void BatchInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KafkaConsumerServer.BatchInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BatchInfo::CopyFrom(const BatchInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KafkaConsumerServer.BatchInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchInfo::IsInitialized() const {
  return true;
}

void BatchInfo::Swap(BatchInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BatchInfo::InternalSwap(BatchInfo* other) {
  using std::swap;
  errormessage_.Swap(&other->errormessage_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(lastoffset_, other->lastoffset_);
  swap(eof_, other->eof_);
  swap(errorcode_, other->errorcode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BatchInfo::GetMetadata() const {
  protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Empty::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Empty::Empty()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kafka_2eproto::scc_info_Empty.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KafkaConsumerServer.Empty)
}
Empty::Empty(const Empty& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:KafkaConsumerServer.Empty)
}

void Empty::SharedCtor() {
}

Empty::~Empty() {
  // @@protoc_insertion_point(destructor:KafkaConsumerServer.Empty)
  SharedDtor();
}

void Empty::SharedDtor() {
}

void Empty::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Empty::descriptor() {
  ::protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Empty& Empty::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kafka_2eproto::scc_info_Empty.base);
  return *internal_default_instance();
}


void Empty::Clear() {
// @@protoc_insertion_point(message_clear_start:KafkaConsumerServer.Empty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool Empty::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KafkaConsumerServer.Empty)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:KafkaConsumerServer.Empty)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KafkaConsumerServer.Empty)
  return false;
#undef DO_
}

void Empty::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KafkaConsumerServer.Empty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KafkaConsumerServer.Empty)
}

::google::protobuf::uint8* Empty::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KafkaConsumerServer.Empty)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KafkaConsumerServer.Empty)
  return target;
}

size_t Empty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KafkaConsumerServer.Empty)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Empty::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KafkaConsumerServer.Empty)
  GOOGLE_DCHECK_NE(&from, this);
  const Empty* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Empty>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KafkaConsumerServer.Empty)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KafkaConsumerServer.Empty)
    MergeFrom(*source);
  }
}

void Empty::MergeFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KafkaConsumerServer.Empty)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void Empty::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KafkaConsumerServer.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Empty::CopyFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KafkaConsumerServer.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Empty::IsInitialized() const {
  return true;
}

void Empty::Swap(Empty* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Empty::InternalSwap(Empty* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Empty::GetMetadata() const {
  protobuf_kafka_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kafka_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace KafkaConsumerServer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KafkaConsumerServer::ConsumerJob* Arena::CreateMaybeMessage< ::KafkaConsumerServer::ConsumerJob >(Arena* arena) {
  return Arena::CreateInternal< ::KafkaConsumerServer::ConsumerJob >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KafkaConsumerServer::JobID* Arena::CreateMaybeMessage< ::KafkaConsumerServer::JobID >(Arena* arena) {
  return Arena::CreateInternal< ::KafkaConsumerServer::JobID >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KafkaConsumerServer::BatchData* Arena::CreateMaybeMessage< ::KafkaConsumerServer::BatchData >(Arena* arena) {
  return Arena::CreateInternal< ::KafkaConsumerServer::BatchData >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KafkaConsumerServer::BatchInfo* Arena::CreateMaybeMessage< ::KafkaConsumerServer::BatchInfo >(Arena* arena) {
  return Arena::CreateInternal< ::KafkaConsumerServer::BatchInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KafkaConsumerServer::Empty* Arena::CreateMaybeMessage< ::KafkaConsumerServer::Empty >(Arena* arena) {
  return Arena::CreateInternal< ::KafkaConsumerServer::Empty >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
